using CoFAS.NEW.MES.Core.Business;
using CoFAS.NEW.MES.Core.Entity;
using CoFAS.NEW.MES.Core.Function;
using System;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace CoFAS.NEW.MES.Core
{
    public partial class 작업지시명세 : BaseForm1
    {

        public override void MainFind_DisplayData()
        {
            try
            {
                DevExpressManager.SetCursor(this, Cursors.WaitCursor);

                fpMain.Sheets[0].Rows.Count = 0;

                string str = $@"



SELECT *
, MATERIAL_M_COST  AS '재료관리비'  
,  OUT_M_COST AS '외주관리비' 
, GENERAL_M_COST AS  '일반관리비' 
FROM  (

SELECT * FROM 

(SELECT  품번,LOT, 품명 , 원재료 , SUM(A.QTY_COMPLETE) * A.재료비 AS '주조1(기본)' , 재료비 ,SUM(A.QTY_COMPLETE) as QTY_COMPLETE
,SUM(A.QTY_COMPLETE) * A.재료비  '주조1(BEST)'
,'' as '사상1(기본)'
,'' as '사상1(BEST)'
,'' as '가공1(기본)'
,'' as '가공1(BEST)'
,'' as '바렐세척검사(기본)'
,'' as '바렐세척검사(BEST)'
,'' as '조립검사(기본)'
,'' as '조립검사(BEST)'
,'' as '참조'FROM 
(SELECT DISTINCT 
B.RESOURCE_NO AS '품번',
A.LOT_NO AS LOT,
C.[DESCRIPTION] AS '품명' ,
B.RESOURCE_USED AS '원재료' ,
YEAR(A.ORDER_DATE) AS 년도,
    MONTH(A.ORDER_DATE) AS 월,
A.QTY_COMPLETE,

convert(decimal(18,2),(CONVERT(decimal(18,2),isnull((SELECT  top 1 [qty_per]  FROM [sea_mfg].[dbo].[cproduct_defn] where resource_no = A.RESOURCE_NO and ENG_CHG_CODE ='A' ),'0')))
* CONVERT(int,isnull((SELECT TOP 1 [price] FROM [sea_mfg].[dbo].[prices] where resource_no = (SELECT  top 1 [resource_used]  FROM [sea_mfg].[dbo].[cproduct_defn] where resource_no = A.RESOURCE_NO and ENG_CHG_CODE ='A') order by update_date desc),'0')) 
* ((convert(int,5) /100.0 +1) )) AS '재료비'



FROM [HS_MES].[dbo].[WORK_PERFORMANCE] AS A

INNER JOIN [sea_mfg].[dbo].[cproduct_defn] AS B
ON A.RESOURCE_NO = B.RESOURCE_NO
AND A.QTY_COMPLETE <> 0
INNER JOIN [sea_mfg].[dbo].[RESOURCE] AS C
ON A.RESOURCE_NO = C.RESOURCE_NO

WHERE A.QTY_COMPLETE <> 0) A
GROUP BY A.품번,A.품명,A.원재료, A.재료비,A.LOT
) AS A

INNER JOIN 
(SELECT 
		
	   D.[description]   AS 'D.호기'
    ,A.[RESOURCE_NO]  AS 'RESOURCE_NO'
     ,A.[LOT_NO]       AS 'LOT_NO'
     ,B.[description]  AS 'B.설비명'
     
     ,ISNULL(F.cavity,'0')          AS 'F.CAVITY'   
      ,sum(CONVERT(NUMERIC(18,2),A.[ELECTRICAL_ENERGY])) AS 'A.전력사용량'
      ,sum(CONVERT(NUMERIC(18,2),A.[CYCLE_TIME])) AS 'A.CYCLE_TIME'
	  ,sum(CONVERT(NUMERIC(18,2), ROUND(ISNULL(J.WORK_TIME,0)/60,2))) AS 'WORK_TIME'

	 
,CONVERT(DECIMAL(18,2), sum(ISNULL(ROUND((CONVERT(decimal(18,4), G.HOURLY_WAGE_PER_SECOND) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) * convert(int,J.IN_PER) /CONVERT(INT,F.cavity)),2),0))) AS '직접노무비'
     ,CONVERT(DECIMAL(18,2),sum(ISNULL((ROUND((CONVERT(decimal(18,4), G.HOURLY_WAGE_PER_SECOND) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) * convert(int,J.IN_PER) /CONVERT(INT,F.cavity)),2) * ((CONVERT(decimal(18,4) ,G.INDIRECT_LABOR_RATIO)) / 100   )),0) ) )    AS '간접노무비'
     ,CONVERT(DECIMAL(18,2),sum(ISNULL((CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)),0) ) )       AS '설비감상비'
     ,CONVERT(DECIMAL(18,2),sum(ISNULL((CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity)) ,0) ) )      AS '건물감상비'
     ,CONVERT(DECIMAL(18,2),sum(ISNULL(((CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity) + CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(INT ,H.EQUIPMENT_COST)/(CONVERT (DECIMAL(18,2),H.EQUIPMENT_AREA)/3.3) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) *CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)) * CONVERT(DECIMAL(18,2),G.REPAIR_RATE)/100),0))) AS '수선비'
     ,CONVERT(DECIMAL(18,2),sum(ISNULL((CONVERT(DECIMAL(18,2),ISNULL(ELECTRICAL_ENERGY,0)) * convert(int,(H.[EQUIPMENT_POWER_RATIO])) ),0)))    AS '전체전력비'
	-- ,ISNULL((CONVERT(DECIMAL(18,2),ISNULL(I.ELEC_USE,0)) * convert(int,(H.[EQUIPMENT_POWER_RATIO]))) ,0)   AS '전체전력비'
     ,CONVERT(DECIMAL(18,2),sum(ISNULL(((CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)
+ 
CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity)
+
(CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)
+
CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity)
* CONVERT(DECIMAL(18,2),G.REPAIR_RATE)/100)
+
CONVERT(DECIMAL(18,2),ISNULL(ELECTRICAL_ENERGY,0)) * convert(int,(H.[EQUIPMENT_POWER_RATIO]))) 
*
CONVERT(DECIMAL(18,2),INDIRECT_EXPENSE_RATIO)/100),0)))   AS '간접경비'

  /*   ,CONVERT(DECIMAL(18,2),sum(ISNULL(((ROUND((CONVERT(decimal(18,4), G.HOURLY_WAGE_PER_SECOND) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) * convert(int,J.IN_PER) /CONVERT(INT,F.cavity)),2))
+
(ROUND((CONVERT(decimal(18,4), G.HOURLY_WAGE_PER_SECOND) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) * convert(int,J.IN_PER) /CONVERT(INT,F.cavity)),2) *  ((CONVERT(decimal(18,4) ,G.INDIRECT_LABOR_RATIO)) / 100   ))
+
(CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity))
+
(CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity))
+
(CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)
+
CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity)
* CONVERT(DECIMAL(18,2),G.REPAIR_RATE)/100)
+
(CONVERT(DECIMAL(18,2),ISNULL(ELECTRICAL_ENERGY,0)) * convert(int,(H.[EQUIPMENT_POWER_RATIO])))
+
((CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)
+ 
CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity)
+
(CONVERT(INT ,H.EQUIPMENT_COST) / CONVERT(INT, H.EQUIPMENT_USE_YEAR) / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) /   CONVERT(INT,F.cavity)
+
CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 / CONVERT(INT, H.EQUIPMENT_OPERATION) /CONVERT(INT,H.EQUIPMENT_OPERATION_DAY) /CONVERT(INT,H.EQUIPMENT_OPERATION_TIME) * CONVERT(DECIMAL(18,2),A.CYCLE_TIME) /   CONVERT(INT,F.cavity)
* CONVERT(DECIMAL(18,2),G.REPAIR_RATE)/100)
+
CONVERT(DECIMAL(18,2),ISNULL(ELECTRICAL_ENERGY,0)) * convert(int,(H.[EQUIPMENT_POWER_RATIO]))) 
*
CONVERT(DECIMAL(18,2),INDIRECT_EXPENSE_RATIO)/100))  ,0)))
 AS '공정비'
*/
	 , FORMAT( AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)), '0') AS 'CYCLE_TIME'
	, ROUND(ISNULL(J.WORK_TIME,0) / 60 / 60 / 24 ,2) /(1*260/12)  AS '시간가동률' 
	
	, CASE WHEN ISNULL(J.WORK_TIME,0) ='0' THEN  '0' ELSE CONVERT(DECIMAL(18,2),J.QTY_COMPLETE) / CONVERT(NUMERIC(18,2), ROUND(ISNULL(J.WORK_TIME,0)/60,2)) / 22 * ISNULL(F.cavity,'0') END AS '성능가동률'
	, (CASE WHEN ISNULL(J.WORK_TIME,0) ='0' THEN  '0' ELSE CONVERT(DECIMAL(18,2),J.QTY_COMPLETE) / CONVERT(NUMERIC(18,2), ROUND(ISNULL(J.WORK_TIME,0)/60,2)) / 22 * ISNULL(F.cavity,'0') END) * ROUND(ISNULL(J.WORK_TIME,0) / 60 / 60 / 24 ,2) /(1*260/12) AS '종합가동률'
	-- 3600 / 샷 사이클 타임 * 가동율 85% * 가동대수 (1대) 
	, FORMAT((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0') AS '성능가동률_BEST'
	-- 직접노무비_BEST 표준임율 (16900원) / 성능가동율(128개) * 1명 
		,FORMAT(convert(DECIMAL(18,2),16900) /  (FORMAT((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0.00')), '0') * J.QTY_COMPLETE AS '직접노무비_BEST'
		-- 직접노무비 * 간접노무비율 (87.3%) 
		,format((convert(DECIMAL(18,2),16900) /  (FORMAT((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0.00'))) * (CONVERT(decimal(18,4) ,G.INDIRECT_LABOR_RATIO) / 100   ), '0')* J.QTY_COMPLETE  AS '간접노무비_BEST'
		--성능가동률 * 시간가동율 (100.0%)
		, FORMAT((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0')  AS '종합가동률_BEST'

		--설비감상비 (757100,998원) / (기계감가상각기준 12년) / 260일 / 22Hr / 종합가동율
		, FORMAT(757100998 /12/22/260/ ((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0)),'0')* J.QTY_COMPLETE  AS '설비감상비_BEST'
		-- 건물감상비 (109) * 980000원 * 5.5배 /40년 /260일 22Hr /종합가동율
		, FORMAT(CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 /260/22/  FORMAT((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0'), '0')* J.QTY_COMPLETE 
		AS '건물감상비_BEST'
		-- (설비감상비 + 건물감상비) * 수선비  ISNULL(CONVERT(DECIMAL(18,2), G.REPAIR_RATE)/100,0)
		, FORMAT((((757100998 /12/22/260/ ((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) *0.85)* ISNULL(F.cavity,'0') *1)) + ((((((109 *980000)*5.5)/ 40) /22)/260)/ ((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) *0.85)* ISNULL(F.cavity,'0') *1))) * CONVERT(DECIMAL(18,2), G.REPAIR_RATE)/100) , '0')* J.QTY_COMPLETE  AS '수선비_BEST'
	
	-- (240kw * 60% + 30kw * 38%) * 전력비(161kw) / 성능가동율
		, FORMAT(((240 * 0.6) + (60 * 0.38) + (30 * 0.38)) * H.EQUIPMENT_POWER_RATIO  /FORMAT( (3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0'),'0') * J.QTY_COMPLETE  AS '전체전력비_BEST'
		
	, (CONVERT(DECIMAL(18,2),sum(ISNULL((CONVERT(DECIMAL(18,2),ISNULL(ELECTRICAL_ENERGY,0)) * convert(int,(H.[EQUIPMENT_POWER_RATIO])) ),0)))) AS '전체전력비_BEST1'

		-- 간접경비 = 설비감상비 + 건불감상비 + 수선비 + 전력비 * 간접경비 (26.9%) convert(DECIMAL(18,2),INDIRECT_EXPENSE_RATIO) /100
	,FORMAT(
		((757100998 /12/22/260/ ((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0)))
		+ (CONVERT(DECIMAL(18,2),H.EQUIPMENT_AREA) * CONVERT(DECIMAL(18,2),H.UNIT_PRICE_PER_PYEONG) * 5.5 /40 /260/22/  FORMAT((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0'))
		+ ((((757100998 /12/22/260/ ((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) *0.85)* ISNULL(F.cavity,'0') *1)) + ((((((109 *980000)*5.5)/ 40) /22)/260)/ ((3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) *0.85)* ISNULL(F.cavity,'0') *1))) * 0.049))
		+ ((240 * 0.6) + (60 * 0.38) + (30 * 0.38)) * H.EQUIPMENT_POWER_RATIO  /FORMAT( (3600/AVG(CONVERT(DECIMAL(18,2),A.CYCLE_TIME)) * 0.85)* ISNULL(F.cavity,0),'0'))
		 * convert(DECIMAL(18,2),INDIRECT_EXPENSE_RATIO) /100
		, '0')* J.QTY_COMPLETE 
	
	AS '간접경비_BEST'
	
	
  
    FROM [HS_MES].[dbo].[ELEC_SHOT] AS A

  INNER JOIN (SELECT RESOURCE_NO , LOT_NO, SUM(QTY_COMPLETE) QTY_COMPLETE  ,SUM(CONVERT(DECIMAL(18,2),IN_PER)) AS IN_PER  , SUM( CONVERT(DECIMAL(18,2),WORK_TIME)) AS WORK_TIME  FROM [HS_MES].[dbo].[WORK_PERFORMANCE] GROUP BY RESOURCE_NO, LOT_NO  ) AS J
  ON A.RESOURCE_NO = J.RESOURCE_NO
  AND A.LOT_NO = J.LOT_NO

   INNER JOIN [sea_mfg].[dbo].[resource] AS B WITH (NOLOCK)
  ON B.resource_no  = A.resource_no
  INNER JOIN [sea_mfg].[dbo].[schedrtg] AS C  WITH (NOLOCK)
  ON C.order_no = A.resource_no 
  AND C.lot = A.LOT_NO
  INNER JOIN [sea_mfg].[dbo].[resource] AS D  WITH (NOLOCK)
  ON C.workcenter =D.resource_no
  INNER JOIN [sea_mfg].[dbo].[demand_mstr_ext] AS E  WITH (NOLOCK)
  ON A.RESOURCE_NO = E.order_no
  AND A.LOT_NO = E.lot
  LEFT OUTER JOIN [sea_mfg].[dbo].[md_mst] AS F  WITH (NOLOCK)
  ON E.code_md = F.code_md 
  LEFT OUTER JOIN [HS_MES].[dbo].[MATERIALCOST_PROCESS] AS G
  ON G.PROCESS_ID = '주조'
  INNER JOIN MATERIALCOST_EQUIPMENT AS H
  ON H.EQUIPMENT_ID ='설비850TON'
  LEFT OUTER JOIN [HS_MES].[dbo].[ELECTRIC_USE] AS I
  ON A.RESOURCE_NO = I.RESOURCE_NO
   
  WHERE    CONVERT(DECIMAL(18,2),ELECTRICAL_ENERGY) <100

  group by D.[description] 
  ,A.[RESOURCE_NO]     
  ,A.[LOT_NO]          
  ,B.[description]      
  ,F.cavity 
  ,J.QTY_COMPLETE
  ,J.WORK_TIME
  ,  g.INDIRECT_LABOR_RATIO
  ,  H.EQUIPMENT_OPERATION
  , H.EQUIPMENT_OPERATION_TIME
  , H.EQUIPMENT_OPERATION_DAY
  ,H.EQUIPMENT_AREA
  ,H.UNIT_PRICE_PER_PYEONG
  , G.REPAIR_RATE
  , H.EQUIPMENT_POWER_RATIO
  , INDIRECT_EXPENSE_RATIO
  ) AS B
 
  ON A.품번 = B.RESOURCE_NO
  AND A.LOT  =B.LOT_NO
  ) AS MST


  INNER JOIN

  COST_BASE_MST AS SUB

  ON MST.RESOURCE_NO = SUB.RESOURCE_NO
";

                StringBuilder sb = new StringBuilder();
                Function.Core.GET_WHERE(this._PAN_WHERE, sb);

                string sql = str /*+ sb.ToString()*/;

                DataTable _DataTable = new CoreBusiness().SELECT(sql);
                fpMain.Sheets[0].Rows.Count = 0;
                if (_DataTable != null && _DataTable.Rows.Count > 0)
                {
                    fpMain.Sheets[0].Visible = false;
                    fpMain.Sheets[0].Rows.Count = _DataTable.Rows.Count;

                    for (int i = 0; i < _DataTable.Rows.Count; i++)
                    {
                        foreach (DataColumn item in _DataTable.Columns)
                        {
                            fpMain.Sheets[0].SetValue(i, item.ColumnName, _DataTable.Rows[i][item.ColumnName]);

                           
                        }


                    }

                    Function.Core._AddItemSUM(fpMain);

                    fpMain.Sheets[0].Visible = true;


                }
                else
                {
                    fpMain.Sheets[0].Rows.Count = 0;
                    CustomMsg.ShowMessage("조회 내역이 없습니다.");
                }
            }
            catch (Exception _Exception)
            {
                CustomMsg.ShowExceptionMessage(_Exception.ToString(), "Error", MessageBoxButtons.OK);
            }
            finally
            {
                DevExpressManager.SetCursor(this, Cursors.Default);
            }
        }

    }
}
