//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoFAS_MES.POP.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoFAS_MES.POP.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _btLoginCancel {
            get {
                return ResourceManager.GetString("_btLoginCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _btLoginOk {
            get {
                return ResourceManager.GetString("_btLoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _btLoginSetting {
            get {
                return ResourceManager.GetString("_btLoginSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _btSettingExit {
            get {
                return ResourceManager.GetString("_btSettingExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _btSettingSave {
            get {
                return ResourceManager.GetString("_btSettingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _ckSettingUserIDSave {
            get {
                return ResourceManager.GetString("_ckSettingUserIDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _ckUserIDSave {
            get {
                return ResourceManager.GetString("_ckUserIDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lbLoginHeader {
            get {
                return ResourceManager.GetString("_lbLoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lbSettingHeader {
            get {
                return ResourceManager.GetString("_lbSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciAccount {
            get {
                return ResourceManager.GetString("_lciAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciPassword {
            get {
                return ResourceManager.GetString("_lciPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingCorpCode {
            get {
                return ResourceManager.GetString("_lciSettingCorpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디비 아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingDBID {
            get {
                return ResourceManager.GetString("_lciSettingDBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디비 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingDBName {
            get {
                return ResourceManager.GetString("_lciSettingDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디비 타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingDBType {
            get {
                return ResourceManager.GetString("_lciSettingDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폰트 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingFont {
            get {
                return ResourceManager.GetString("_lciSettingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingFTPID {
            get {
                return ResourceManager.GetString("_lciSettingFTPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP SERVER IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingFTPSERVERIP {
            get {
                return ResourceManager.GetString("_lciSettingFTPSERVERIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어변환과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingLanguage {
            get {
                return ResourceManager.GetString("_lciSettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 아이피과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingServerIP {
            get {
                return ResourceManager.GetString("_lciSettingServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingUserID {
            get {
                return ResourceManager.GetString("_lciSettingUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _lciSettingUserIDSave {
            get {
                return ResourceManager.GetString("_lciSettingUserIDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgBookMark {
            get {
                return ResourceManager.GetString("_msgBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgBookMarkAdd {
            get {
                return ResourceManager.GetString("_msgBookMarkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기에 추가 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgBookMarkAddMessage {
            get {
                return ResourceManager.GetString("_msgBookMarkAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgBookMarkDelete {
            get {
                return ResourceManager.GetString("_msgBookMarkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기에 삭제 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgBookMarkDeleteMessage {
            get {
                return ResourceManager.GetString("_msgBookMarkDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 메뉴 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgBookMarkMessage {
            get {
                return ResourceManager.GetString("_msgBookMarkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 계정정보 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgLoginMessage {
            get {
                return ResourceManager.GetString("_msgLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메세지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgMessage {
            get {
                return ResourceManager.GetString("_msgMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgNotice {
            get {
                return ResourceManager.GetString("_msgNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _msgSystemClose {
            get {
                return ResourceManager.GetString("_msgSystemClose", resourceCulture);
            }
        }
    }
}
